package dev.burikk.carrentz.common;

import java.util.Arrays;
import java.util.List;

/**
 * @author Muhammad Irfan
 * @since 19/01/2022 16.25
 */
public class City {
    public static final List<String> CITIES = Arrays.asList(
            "Gianyar",
            "Bangli",
            "Buleleng",
            "Tabanan",
            "Karangasem",
            "Badung",
            "Jembrana",
            "Klungkung",
            "Denpasar",
            "Bangka Selatan",
            "Bangka Barat",
            "Belitung",
            "Pangkal Pinang",
            "Bangka Tengah",
            "Bangka",
            "Belitung Timur",
            "Lebak",
            "Serang",
            "Tangerang",
            "Pandeglang",
            "Tangerang Selatan",
            "Cilegon",
            "Seluma",
            "Bengkulu Tengah",
            "Bengkulu",
            "Muko Muko",
            "Rejang Lebong",
            "Kaur",
            "Bengkulu Selatan",
            "Kepahiang",
            "Lebong",
            "Bengkulu Utara",
            "Gunung Kidul",
            "Yogyakarta",
            "Kulon Progo",
            "Sleman",
            "Bantul",
            "Jakarta Selatan",
            "Jakarta Utara",
            "Jakarta Pusat",
            "Jakarta Barat",
            "Jakarta Timur",
            "Kepulauan Seribu",
            "Boalemo",
            "Pohuwato",
            "Gorontalo Utara",
            "Gorontalo",
            "Bone Bolango",
            "Tebo",
            "Tanjung Jabung Barat",
            "Merangin",
            "Jambi",
            "Bungo",
            "Sungaipenuh",
            "Muaro Jambi",
            "Kerinci",
            "Sarolangun",
            "Tanjung Jabung Timur",
            "Batang Hari",
            "Indramayu",
            "Cirebon",
            "Cianjur",
            "Sukabumi",
            "Purwakarta",
            "Garut",
            "Sumedang",
            "Bandung",
            "Karawang",
            "Bogor",
            "Tasikmalaya",
            "Bekasi",
            "Depok",
            "Subang",
            "Ciamis",
            "Majalengka",
            "Kuningan",
            "Bandung Barat",
            "Pangandaran",
            "Banjar",
            "Cimahi",
            "Wonogiri",
            "Batang",
            "Wonosobo",
            "Boyolali",
            "Klaten",
            "Demak",
            "Pekalongan",
            "Temanggung",
            "Grobogan",
            "Pati",
            "Magelang",
            "Sukoharjo",
            "Kendal",
            "Jepara",
            "Pemalang",
            "Tegal",
            "Banyumas",
            "Banjarnegara",
            "Brebes",
            "Cilacap",
            "Semarang",
            "Kudus",
            "Blora",
            "Salatiga",
            "Karanganyar",
            "Sragen",
            "Rembang",
            "Kebumen",
            "Surakarta",
            "Purbalingga",
            "Purworejo",
            "Bangkalan",
            "Banyuwangi",
            "Batu",
            "Blitar",
            "Bojonegoro",
            "Bondowoso",
            "Gresik",
            "Jember",
            "Jombang",
            "Kediri",
            "Lamongan",
            "Lumajang",
            "Madiun",
            "Magetan",
            "Malang",
            "Mojokerto",
            "Nganjuk",
            "Ngawi",
            "Pacitan",
            "Pamekasan",
            "Pasuruan",
            "Ponorogo",
            "Probolinggo",
            "Sampang",
            "Sidoarjo",
            "Situbondo",
            "Sumenep",
            "Surabaya",
            "Trenggalek",
            "Tuban",
            "Tulungagung",
            "Bengkayang",
            "Kapuas Hulu",
            "Kayong Utara",
            "Ketapang",
            "Kubu Raya",
            "Landak",
            "Melawi",
            "Mempawah",
            "Pontianak",
            "Sambas",
            "Sanggau",
            "Sekadau",
            "Singkawang",
            "Sintang",
            "Balangan",
            "Banjarbaru",
            "Banjarmasin",
            "Barito Kuala",
            "Hulu Sungai Selatan",
            "Hulu Sungai Tengah",
            "Hulu Sungai Utara",
            "Kotabaru",
            "Tabalong",
            "Tanah Bumbu",
            "Tanah Laut",
            "Tapin",
            "Barito Selatan",
            "Barito Timur",
            "Barito Utara",
            "Gunung Mas",
            "Kapuas",
            "Katingan",
            "Kotawaringin Barat",
            "Kotawaringin Timur",
            "Lamandau",
            "Murung Raya",
            "Palangka Raya",
            "Pulang Pisau",
            "Seruyan",
            "Sukamara",
            "Balikpapan",
            "Berau",
            "Bontang",
            "Kutai Barat",
            "Kutai Kartanegara",
            "Kutai Timur",
            "Mahakam Ulu",
            "Paser",
            "Penajam Paser Utara",
            "Samarinda",
            "Bulungan",
            "Malinau",
            "Nunukan",
            "Tana Tidung",
            "Tarakan",
            "Batam",
            "Bintan",
            "Karimun",
            "Kepulauan Anambas",
            "Lingga",
            "Natuna",
            "Tanjung Pinang",
            "Bandar Lampung",
            "Lampung Barat",
            "Lampung Selatan",
            "Lampung Tengah",
            "Lampung Timur",
            "Lampung Utara",
            "Mesuji",
            "Metro",
            "Pesawaran",
            "Pesisir Barat",
            "Pringsewu",
            "Tanggamus",
            "Tulang Bawang",
            "Tulang Bawang Barat",
            "Way Kanan",
            "Ambon",
            "Buru",
            "Buru Selatan",
            "Kepulauan Aru",
            "Maluku Barat Daya",
            "Maluku Tengah",
            "Maluku Tenggara",
            "Maluku Tenggara Barat",
            "Seram Bagian Barat",
            "Seram Bagian Timur",
            "Tual",
            "Halmahera Barat",
            "Halmahera Selatan",
            "Halmahera Tengah",
            "Halmahera Timur",
            "Halmahera Utara",
            "Kepulauan Sula",
            "Pulau Morotai",
            "Pulau Taliabu",
            "Ternate",
            "Tidore Kepulauan",
            "Aceh Barat",
            "Aceh Barat Daya",
            "Aceh Besar",
            "Aceh Jaya",
            "Aceh Selatan",
            "Aceh Singkil",
            "Aceh Tamiang",
            "Aceh Tengah",
            "Aceh Tenggara",
            "Aceh Timur",
            "Aceh Utara",
            "Banda Aceh",
            "Bener Meriah",
            "Bireuen",
            "Gayo Lues",
            "Lhokseumawe",
            "Nagan Raya",
            "Pidie",
            "Pidie Jaya",
            "Sabang",
            "Simeulue",
            "Subulussalam",
            "Bima",
            "Dompu",
            "Lombok Barat",
            "Lombok Tengah",
            "Lombok Timur",
            "Lombok Utara",
            "Mataram",
            "Sumbawa",
            "Sumbawa Barat",
            "Alor",
            "Belu",
            "Ende",
            "Ende",
            "Flores Timur",
            "Flores Timur",
            "Kupang",
            "Lembata",
            "Malaka",
            "Manggarai",
            "Manggarai Barat",
            "Manggarai Timur",
            "Nagekeo",
            "Ngada",
            "Rote Ndao",
            "Sabu Raijua",
            "Sikka",
            "Sumba Barat",
            "Sumba Barat Daya",
            "Sumba Tengah",
            "Sumba Timur",
            "Timor Tengah Selatan",
            "Timor Tengah Utara",
            "Asmat",
            "Biak Numfor",
            "Boven Digoel",
            "Deiyai",
            "Dogiyai",
            "Intan Jaya",
            "Jayapura",
            "Jayawijaya",
            "Keerom",
            "Kepulauan Yapen",
            "Lanny Jaya",
            "Mamberamo Raya",
            "Mamberamo Tengah",
            "Mappi",
            "Merauke",
            "Mimika",
            "Nabire",
            "Nduga",
            "Paniai",
            "Pegunungan Bintang",
            "Puncak",
            "Puncak Jaya",
            "Sarmi",
            "Supiori",
            "Tolikara",
            "Waropen",
            "Yahukimo",
            "Yalimo",
            "Fakfak",
            "Kaimana",
            "Manokwari",
            "Manokwari Selatan",
            "Maybrat",
            "Pegunungan Arfak",
            "Raja Ampat",
            "Sorong",
            "Sorong Selatan",
            "Tambrauw",
            "Teluk Bintuni",
            "Teluk Wondama",
            "Bengkalis",
            "Dumai",
            "Indragiri Hilir",
            "Indragiri Hulu",
            "Kampar",
            "Kepulauan Meranti",
            "Kuantan Singingi",
            "Pekanbaru",
            "Pelalawan",
            "Rokan Hilir",
            "Rokan Hulu",
            "Siak",
            "Majene",
            "Mamasa",
            "Mamuju",
            "Mamuju Tengah",
            "Mamuju Utara",
            "Polewali Mandar",
            "Bantaeng",
            "Barru",
            "Bone",
            "Bulukumba",
            "Enrekang",
            "Gowa",
            "Jeneponto",
            "Kepulauan Selayar",
            "Luwu",
            "Luwu Timur",
            "Luwu Utara",
            "Makassar",
            "Maros",
            "Palopo",
            "Pangkajene Kepulauan",
            "Parepare",
            "Pinrang",
            "Sidenreng Rappang",
            "Sinjai",
            "Soppeng",
            "Takalar",
            "Tana Toraja",
            "Toraja Utara",
            "Wajo",
            "Banggai",
            "Banggai Kepulauan",
            "Banggai Laut",
            "Buol",
            "Donggala",
            "Morowali",
            "Morowali Utara",
            "Palu",
            "Parigi Moutong",
            "Poso",
            "Sigi",
            "Tojo Una-Una",
            "Toli-Toli",
            "Bau-Bau",
            "Bombana",
            "Buton",
            "Buton Selatan",
            "Buton Tengah",
            "Buton Utara",
            "Kendari",
            "Kolaka",
            "Kolaka Timur",
            "Kolaka Utara",
            "Konawe",
            "Konawe Kepulauan",
            "Konawe Selatan",
            "Konawe Utara",
            "Muna",
            "Muna Barat",
            "Wakatobi",
            "Bitung",
            "Bolaang Mongondow",
            "Bolaang Mongondow Selatan",
            "Bolaang Mongondow Timur",
            "Bolaang Mongondow Utara",
            "Kepulauan Sangihe",
            "Kepulauan Siau Tagulandang Biaro (Sitaro)",
            "Kepulauan Talaud",
            "Kotamobagu",
            "Manado",
            "Minahasa",
            "Minahasa Selatan",
            "Minahasa Tenggara",
            "Minahasa Utara",
            "Tomohon",
            "Agam",
            "Bukittinggi",
            "Dharmasraya",
            "Kepulauan Mentawai",
            "Lima Puluh Kota",
            "Padang",
            "Padang Panjang",
            "Padang Pariaman",
            "Pariaman",
            "Pasaman",
            "Pasaman Barat",
            "Payakumbuh",
            "Pesisir Selatan",
            "Sawah Lunto",
            "Sijunjung",
            "Solok",
            "Solok Selatan",
            "Tanah Datar",
            "Banyuasin",
            "Empat Lawang",
            "Lahat",
            "Lubuk Linggau",
            "Muara Enim",
            "Musi Banyuasin",
            "Musi Rawas",
            "Musi Rawas Utara",
            "Ogan Ilir",
            "Ogan Komering Ilir",
            "Ogan Komering Ulu",
            "Ogan Komering Ulu Selatan",
            "Ogan Komering Ulu Timur",
            "Pagar Alam",
            "Palembang",
            "Penukal Abab Lematang Ilir",
            "Prabumulih",
            "Asahan",
            "Batu Bara",
            "Binjai",
            "Dairi",
            "Deli Serdang",
            "Gunungsitoli",
            "Humbang Hasundutan",
            "Karo",
            "Labuhanbatu",
            "Labuhanbatu Selatan",
            "Labuhanbatu Utara",
            "Langkat",
            "Mandailing Natal",
            "Medan",
            "Nias",
            "Nias Barat",
            "Nias Selatan",
            "Nias Utara",
            "Padang Lawas",
            "Padang Lawas Utara",
            "Padang Sidempuan",
            "Pakpak Bharat",
            "Pematang Siantar",
            "Samosir",
            "Serdang Bedagai",
            "Sibolga",
            "Simalungun",
            "Tanjung Balai",
            "Tapanuli Selatan",
            "Tapanuli Tengah",
            "Tapanuli Utara",
            "Tebing Tinggi",
            "Toba Samosir"
    );
}