package dev.burikk.carrentz.common;

import java.util.Arrays;
import java.util.List;

/**
 * @author Muhammad Irfan
 * @since 12/04/2020 06.24
 */
public class DialCode {
    public static final List<DialCode> DIAL_CODES = Arrays.asList(
            new DialCode("AF", "Afghanistan", "+93"),
            new DialCode("AL", "Albania", "+355"),
            new DialCode("DZ", "Algeria", "+213"),
            new DialCode("AS", "American Samoa", "+1684"),
            new DialCode("AD", "Andorra", "+376"),
            new DialCode("AO", "Angola", "+244"),
            new DialCode("AI", "Anguilla", "+1264"),
            new DialCode("AQ", "Antarctica", "+672"),
            new DialCode("AG", "Antigua and Barbuda", "+1268"),
            new DialCode("AR", "Argentina", "+54"),
            new DialCode("AM", "Armenia", "+374"),
            new DialCode("AW", "Aruba", "+297"),
            new DialCode("AU", "Australia", "+61"),
            new DialCode("AT", "Austria", "+43"),
            new DialCode("AZ", "Azerbaijan", "+994"),
            new DialCode("BS", "Bahamas", "+1242"),
            new DialCode("BH", "Bahrain", "+973"),
            new DialCode("BD", "Bangladesh", "+880"),
            new DialCode("BB", "Barbados", "+1246"),
            new DialCode("BY", "Belarus", "+375"),
            new DialCode("BE", "Belgium", "+32"),
            new DialCode("BZ", "Belize", "+501"),
            new DialCode("BJ", "Benin", "+229"),
            new DialCode("BM", "Bermuda", "+1441"),
            new DialCode("BT", "Bhutan", "+975"),
            new DialCode("BO", "Bolivia", "+591"),
            new DialCode("BQ", "Bonaire, Sint Eustatius and Saba", "+599"),
            new DialCode("BA", "Bosnia and Herzegovina", "+387"),
            new DialCode("BW", "Botswana", "+267"),
            new DialCode("BV", "Bouvet Island", "+47"),
            new DialCode("BR", "Brazil", "+55"),
            new DialCode("IO", "British Indian Ocean Territory", "+246"),
            new DialCode("VG", "British Virgin Islands", "+1284"),
            new DialCode("BN", "Brunei Darussalam", "+673"),
            new DialCode("BG", "Bulgaria", "+359"),
            new DialCode("BF", "Burkina Faso", "+226"),
            new DialCode("BI", "Burundi", "+257"),
            new DialCode("CV", "Cabo Verde", "+238"),
            new DialCode("KH", "Cambodia", "+855"),
            new DialCode("CM", "Cameroon", "+237"),
            new DialCode("CA", "Canada", "+1"),
            new DialCode("KY", "Cayman Islands", "+1345"),
            new DialCode("CF", "Central African Republic", "+236"),
            new DialCode("TD", "Chad", "+235"),
            new DialCode("CL", "Chile", "+56"),
            new DialCode("CN", "China", "+86"),
            new DialCode("CX", "Christmas Island", "+61"),
            new DialCode("CC", "Cocos (Keeling) Islands", "+61"),
            new DialCode("CO", "Colombia", "+57"),
            new DialCode("KM", "Comoros", "+269"),
            new DialCode("CG", "Congo", "+242"),
            new DialCode("CK", "Cook Islands", "+682"),
            new DialCode("CR", "Costa Rica", "+506"),
            new DialCode("CI", "Cote d' Ivoire", "+225"),
            new DialCode("HR", "Croatia", "+385"),
            new DialCode("CU", "Cuba", "+53"),
            new DialCode("CY", "Cyprus", "+357"),
            new DialCode("CZ", "Czechia", "+420"),
            new DialCode("KP", "Democratic People's Republic of Korea", "+850"),
            new DialCode("CD", "Democratic Republic of the Congo", "+243"),
            new DialCode("DK", "Denmark", "+45"),
            new DialCode("DJ", "Djibouti", "+253"),
            new DialCode("DM", "Dominica", "+1767"),
            new DialCode("DO", "Dominican Republic", "+1809"),
            new DialCode("EC", "Ecuador", "+593"),
            new DialCode("EG", "Egypt", "+20"),
            new DialCode("SV", "El Salvador", "+503"),
            new DialCode("GQ", "Equatorial Guinea", "+240"),
            new DialCode("ER", "Eritrea", "+291"),
            new DialCode("EE", "Estonia", "+372"),
            new DialCode("SZ", "Eswatini", "+268"),
            new DialCode("ET", "Ethiopia", "+251"),
            new DialCode("FK", "Falkland Islands", "+500"),
            new DialCode("FO", "Faroe Islands", "+298"),
            new DialCode("FJ", "Fiji", "+679"),
            new DialCode("FI", "Finland", "+358"),
            new DialCode("FR", "France", "+33"),
            new DialCode("GF", "French Guiana", "+594"),
            new DialCode("PF", "French Polynesia", "+689"),
            new DialCode("TF", "French Southern Territories", "+262"),
            new DialCode("GA", "Gabon", "+241"),
            new DialCode("GM", "Gambia", "+220"),
            new DialCode("GE", "Georgia", "+995"),
            new DialCode("DE", "Germany", "+49"),
            new DialCode("GH", "Ghana", "+233"),
            new DialCode("GI", "Gibraltar", "+350"),
            new DialCode("GR", "Greece", "+30"),
            new DialCode("GL", "Greenland", "+299"),
            new DialCode("GD", "Grenada", "+1473"),
            new DialCode("GP", "Guadeloupe", "+590"),
            new DialCode("GU", "Guam", "+1671"),
            new DialCode("GT", "Guatemala", "+502"),
            new DialCode("GG", "Guernsey", "+44"),
            new DialCode("GN", "Guinea", "+224"),
            new DialCode("GW", "Guinea-Bissau", "+245"),
            new DialCode("GY", "Guyana", "+592"),
            new DialCode("HT", "Haiti", "+509"),
            new DialCode("HM", "Heard Island and McDonald Islands", "+672"),
            new DialCode("VA", "Holy See", "+3906"),
            new DialCode("HN", "Honduras", "+504"),
            new DialCode("HK", "Hongkong", "+852"),
            new DialCode("HU", "Hungary", "+36"),
            new DialCode("IS", "Iceland", "+354"),
            new DialCode("IN", "India", "+91"),
            new DialCode("ID", "Indonesia", "+62"),
            new DialCode("IR", "Iran", "+98"),
            new DialCode("IQ", "Iraq", "+964"),
            new DialCode("IE", "Ireland", "+353"),
            new DialCode("IM", "Isle of Man", "+44"),
            new DialCode("IL", "Israel", "+972"),
            new DialCode("IT", "Italy", "+39"),
            new DialCode("JM", "Jamaica", "+1876"),
            new DialCode("JP", "Japan", "+81"),
            new DialCode("JE", "Jersey", "+44"),
            new DialCode("JO", "Jordan", "+962"),
            new DialCode("KZ", "Kazakhstan", "+7"),
            new DialCode("KE", "Kenya", "+254"),
            new DialCode("KI", "Kiribati", "+686"),
            new DialCode("KW", "Kuwait", "+965"),
            new DialCode("KG", "Kyrgyzstan", "+996"),
            new DialCode("LA", "Lao People's Democratic Republic", "+856"),
            new DialCode("LV", "Latvia", "+371"),
            new DialCode("LB", "Lebanon", "+961"),
            new DialCode("LS", "Lesotho", "+266"),
            new DialCode("LR", "Liberia", "+231"),
            new DialCode("LY", "Libya", "+218"),
            new DialCode("LI", "Liechtenstein", "+423"),
            new DialCode("LT", "Lithuania", "+370"),
            new DialCode("LU", "Luxembourg", "+352"),
            new DialCode("MO", "Macao", "+853"),
            new DialCode("MG", "Madagascar", "+261"),
            new DialCode("MW", "Malawi", "+265"),
            new DialCode("MY", "Malaysia", "+60"),
            new DialCode("MV", "Maldives", "+960"),
            new DialCode("ML", "Mali", "+223"),
            new DialCode("MT", "Malta", "+356"),
            new DialCode("MH", "Marshall Islands", "+692"),
            new DialCode("MQ", "Martinique", "+596"),
            new DialCode("MR", "Mauritania", "+222"),
            new DialCode("MU", "Mauritius", "+230"),
            new DialCode("YT", "Mayotte", "+262"),
            new DialCode("MX", "Mexico", "+52"),
            new DialCode("FM", "Micronesia", "+691"),
            new DialCode("MC", "Monaco", "+377"),
            new DialCode("MN", "Mongolia", "+976"),
            new DialCode("ME", "Montenegro", "+382"),
            new DialCode("MS", "Montserrat", "+1664"),
            new DialCode("MA", "Morocco", "+212"),
            new DialCode("MZ", "Mozambique", "+258"),
            new DialCode("MM", "Myanmar", "+95"),
            new DialCode("NA", "Namibia", "+264"),
            new DialCode("NR", "Nauru", "+674"),
            new DialCode("NP", "Nepal", "+977"),
            new DialCode("NL", "Netherlands", "+31"),
            new DialCode("NC", "New Caledonia", "+687"),
            new DialCode("NZ", "New Zealand", "+64"),
            new DialCode("NI", "Nicaragua", "+505"),
            new DialCode("NE", "Niger", "+227"),
            new DialCode("NG", "Nigeria", "+234"),
            new DialCode("NU", "Niue", "+683"),
            new DialCode("NF", "Norfolk Island", "+672"),
            new DialCode("MP", "Northern Mariana Islands", "+1670"),
            new DialCode("NO", "Norway", "+47"),
            new DialCode("OM", "Oman", "+968"),
            new DialCode("PK", "Pakistan", "+92"),
            new DialCode("PW", "Palau", "+680"),
            new DialCode("PA", "Panama", "+507"),
            new DialCode("PG", "Papua New Guinea", "+675"),
            new DialCode("PY", "Paraguay", "+595"),
            new DialCode("PE", "Peru", "+51"),
            new DialCode("PH", "Philippines", "+63"),
            new DialCode("PN", "Pitcairn", "+870"),
            new DialCode("PL", "Poland", "+48"),
            new DialCode("PT", "Portugal", "+351"),
            new DialCode("PR", "Puerto Rico", "+1"),
            new DialCode("QA", "Qatar", "+974"),
            new DialCode("KR", "Republic of Korea", "+82"),
            new DialCode("MD", "Republic of Moldova", "+373"),
            new DialCode("RO", "Romania", "+40"),
            new DialCode("RU", "Russian Federation", "+7"),
            new DialCode("RW", "Rwanda", "+250"),
            new DialCode("SH", "Saint Helena", "+290"),
            new DialCode("KN", "Saint Kitts and Nevis", "+1869"),
            new DialCode("LC", "Saint Lucia", "+1758"),
            new DialCode("MF", "Saint Martin", "+590"),
            new DialCode("PM", "Saint Pierre and Miquelon", "+508"),
            new DialCode("VC", "Saint Vincent and the Grenadines", "+1784"),
            new DialCode("WS", "Samoa", "+685"),
            new DialCode("SM", "San Marino", "+378"),
            new DialCode("ST", "Sao Tome and Principe", "+239"),
            new DialCode("SA", "Saudi Arabia", "+966"),
            new DialCode("SN", "Senegal", "+221"),
            new DialCode("RS", "Serbia", "+381"),
            new DialCode("SC", "Seychelles", "+248"),
            new DialCode("SL", "Sierra Leone", "+232"),
            new DialCode("SG", "Singapore", "+65"),
            new DialCode("SX", "Sint Maarten", "+1721"),
            new DialCode("SK", "Slovakia", "+421"),
            new DialCode("SI", "Slovenia", "+386"),
            new DialCode("SB", "Solomon Islands", "+677"),
            new DialCode("SO", "Somalia", "+252"),
            new DialCode("ZA", "South Africa", "+27"),
            new DialCode("GS", "South Georgia and the South Sandwich Islands", "+500"),
            new DialCode("SS", "South Sudan", "+211"),
            new DialCode("ES", "Spain", "+34"),
            new DialCode("LK", "Sri Lanka", "+94"),
            new DialCode("PS", "State of Palestine", "+970"),
            new DialCode("SD", "Sudan", "+249"),
            new DialCode("SR", "Suriname", "+597"),
            new DialCode("SJ", "Svalbard and Jan Mayen Islands", "+47"),
            new DialCode("SE", "Sweden", "+46"),
            new DialCode("CH", "Switzerland", "+41"),
            new DialCode("SY", "Syrian Arab Republic", "+963"),
            new DialCode("TW", "Taiwan", "+886"),
            new DialCode("TJ", "Tajikistan", "+992"),
            new DialCode("TH", "Thailand", "+66"),
            new DialCode("MK", "The former Yugoslav Republic of Macedonia", "+389"),
            new DialCode("TL", "Timor-Leste", "+670"),
            new DialCode("TG", "Togo", "+228"),
            new DialCode("TK", "Tokelau", "+690"),
            new DialCode("TO", "Tonga", "+676"),
            new DialCode("TT", "Trinidad and Tobago", "+1868"),
            new DialCode("TN", "Tunisia", "+216"),
            new DialCode("TR", "Turkey", "+90"),
            new DialCode("TM", "Turkmenistan", "+993"),
            new DialCode("TC", "Turks and Caicos Islands", "+1649"),
            new DialCode("TV", "Tuvalu", "+688"),
            new DialCode("UG", "Uganda", "+256"),
            new DialCode("UA", "Ukraine", "+380"),
            new DialCode("AE", "United Arab Emirates", "+971"),
            new DialCode("TZ", "United Republic of Tanzania", "+255"),
            new DialCode("US", "United States of America", "+1"),
            new DialCode("VI", "United States Virgin Islands", "+1340"),
            new DialCode("UY", "Uruguay", "+598"),
            new DialCode("UZ", "Uzbekistan", "+998"),
            new DialCode("VU", "Vanuatu", "+678"),
            new DialCode("VE", "Venezuela", "+58"),
            new DialCode("VN", "Vietnam", "+84"),
            new DialCode("WF", "Wallis and Futuna Islands", "+681"),
            new DialCode("EH", "Western Sahara", "+212"),
            new DialCode("YE", "Yemen", "+967"),
            new DialCode("ZM", "Zambia", "+260"),
            new DialCode("ZW", "Zimbabwe", "+263")
    );

    private String countryCode;
    private String countryName;
    private String dialCode;

    private DialCode(
            String countryCode,
            String countryName,
            String dialCode
    ) {
        this.countryCode = countryCode;
        this.countryName = countryName;
        this.dialCode = dialCode;
    }

    public String getCountryCode() {
        return this.countryCode;
    }

    public String getCountryName() {
        return this.countryName;
    }

    public String getDialCode() {
        return this.dialCode;
    }
}